# Generated by Django 3.0.8 on 2020-07-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('discount_value', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
